#pragma once

#define RTRC_ANONYMOUS_NAME_CAT(A, B) RTRC_ANONYMOUS_NAME_CAT_IMPL(A, B)
#define RTRC_ANONYMOUS_NAME_CAT_IMPL(A, B) A##B

#ifdef __COUNTER__
#define RTRC_ANONYMOUS_NAME(STR) RTRC_ANONYMOUS_NAME_CAT(STR, __COUNTER__)
#else
#define RTRC_ANONYMOUS_NAME(STR) RTRC_ANONYMOUS_NAME_CAT(STR, __LINE__)
#endif
